config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'posts#index'

  devise_for :users

  resources :posts, only: %i[index new create show] do
    scope module: :posts do
      resources :comments, only: :create
      resources :likes, only: %i[create destroy]
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3 }
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :creator, class_name: 'User'
  belongs_to :category
  has_many :comments, class_name: 'PostComment', dependent: :destroy
  has_many :likes, class_name: 'PostLike', dependent: :destroy

  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true, length: { minimum: 5 }

  scope :by_recently_created, -> { order(id: :desc) }
end

app/models/post_comment.rb
# frozen_string_literal: true

class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post, counter_cache: :count_of_comments
  has_ancestry

  validates :content, presence: true, length: { minimum: 5 }
end

app/models/post_like.rb
# frozen_string_literal: true

class PostLike < ApplicationRecord
  belongs_to :post, counter_cache: :count_of_likes
  belongs_to :user

  scope :by_user_and_post, ->(user, post) { where post: post, user: user }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable,
         :recoverable, :validatable

  has_many :posts, foreign_key: 'creator_id', dependent: :destroy, inverse_of: :creator
  has_many :comments, dependent: :destroy, class_name: 'PostComment'
  has_many :likes, dependent: :destroy, inverse_of: :user, class_name: 'PostLike'
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include ActionView::RecordIdentifier

  add_flash_types :success, :warning, :danger, :info
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  def create
    authenticate_user!
    set_post!
    PostLike.create! user: current_user, post: @post unless PostLike.user_like_post(current_user, @post).any?

    redirect_to @post
  end

  def destroy
    authenticate_user!
    set_post!
    PostLike.user_like_post(current_user, @post).delete_all
    redirect_to @post
  end

  private

  def set_post!
    @post = Post.find params[:post_id]
  end
end

app/controllers/posts/comments_controller.rb
# frozen_string_literal: true

module Posts
  class CommentsController < ApplicationController
    def create
      authenticate_user!
      @post = Post.find params[:post_id]
      @parent_comment = PostComment.find_by id: params[:comment_id]

      @new_comment = @post.comments.build(comment_params)
      @new_comment.user = current_user
      @new_comment.parent = @parent_comment

      if @new_comment.save
        redirect_to post_path(@post, anchor: dom_id(@new_comment)), success: t('.success')
      else
        redirect_to @post, warning: @new_comment.errors.full_messages.join(' ')
      end
    end

    private

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:post_comment).permit(:content)
    end
  end
end

app/controllers/posts/likes_controller.rb
# frozen_string_literal: true

class Posts::LikesController < ApplicationController
  def create
    authenticate_user!
    set_post!
    PostLike.create! user: current_user, post: @post unless PostLike.by_user_and_post(current_user, @post).any?

    redirect_to @post
  end

  def destroy
    authenticate_user!
    set_post!
    PostLike.by_user_and_post(current_user, @post).destroy_all
    redirect_to @post
  end

  private

  def set_post!
    @post = Post.find params[:post_id]
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  def index
    @posts = Post.by_recently_created.includes :creator
  end

  def new
    authenticate_user!
    @post = current_user.posts.new
  end

  def create
    authenticate_user!
    @post = current_user.posts.new post_params
    if @post.save
      redirect_to root_path, success: t('.success')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @post = Post.find params[:id]
    set_like # only for hexlet check
    @new_comment = @post.comments.build
    @comments = comments_tree
    @post = @post.decorate
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :category_id)
  end

  def comments_tree
    PostComment.includes(:user).arrange post: @post, order: :created_at
  end

  # only for hexlet check
  def set_like
    @like = PostLike.by_user_and_post(current_user, @post)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html.h-100
  head
    title = t('.title')
    == csrf_meta_tags
    == csp_meta_tag
    meta name="keywords" content="template language"
    meta name="author" content='author'
    meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"
    = stylesheet_pack_tag 'application', media: 'all'
    = javascript_pack_tag 'application'

  body.d-flex.flex-column.h-100

    = render 'layouts/shared/nav'

    .container.my-4

      = render 'layouts/shared/alerts'
      == yield

    footer.bg-dark.text-light.mt-auto
      .container-xl
        .row.py-2
          '&copy; @hexlet-student
          = Time.current.year

app/views/layouts/shared/_alerts.html.slim
- if flash.any?
  .container.my-2
    - flash.each do |message_type, msg|
      - case message_type.to_s
      - when 'alert'
        .alert.alert-danger
          = msg
      - when 'notice'
        .alert.alert-success
          = msg
      - else
        div class = "alert alert-#{message_type}"
          = msg

app/views/layouts/shared/_nav.html.slim
.container.mb-2
  .d-flex.flex-wrap.align-items-center.py-2.border-bottom
    .navbar.navbar-expand-md.navbar-light.me-auto
      = link_to root_path, class: 'navbar-brand me-md-4'
        = image_tag asset_pack_path('media/images/logo.png'), width: 30, alt: t('.hexlet logo')
    ul.nav.nav-pills
      - if signed_in?
        li.nav-item.me-2
          = link_to t('.add_post'), new_post_path, class: 'nav-link link-dark'
        li.nav-item.me-2
          = link_to t('.sign_out'), destroy_user_session_path, class: 'nav-link link-dark', method: :delete
      - else
        li.nav-item.me-2
          = link_to t('.sign_in'), new_user_session_path, class: 'nav-link link-dark'
        li.nav-item.me-2
          = link_to t('.register'), new_user_registration_path, class: 'nav-link link-dark'

app/views/posts/_comment.html.slim
/ required variables: comment, subtree, new_comment

.card.mt-4.mb-3 id=dom_id(comment)
  .card-body
    .card-text.mb-2
      span.me-2.fw-bold = comment.user.email
      span = distance_of_time_in_words_to_now comment.created_at
    hr
    .card-text.mb-2 = comment.content
    hr
    .card-text
      = link_to t('.answer'), "#new_#{dom_id comment}", class: 'd-block small collapsed text-muted', 'data-bs-toggle' => 'collapse', 'aria-expanded' => false

      .collapse.mt-2 id="new_#{dom_id(comment)}" data-bs-target="#new_#{dom_id(comment)}"
        - if current_user
          = render 'comment_form', comment: new_comment, url: post_comments_path(comment.post, comment_id: comment.id)
        - else
          .d-flex
            span = t('.requires')
            = link_to t('.sign_in'), new_user_session_path, class: 'mx-1'
    .ms-4.me-2
      - subtree.each do |comment, subtree|
        = render 'comment', comment: comment, subtree: subtree, new_comment: new_comment

app/views/posts/_comment_form.html.slim
= simple_form_for comment, url: url, id: dom_id(comment) do |f|
  .form-controls
    = f.input :content, as: :text, label: false
  .form-actions
    = f.submit class: 'btn btn-primary mb-4 mt-1'

app/views/posts/index.html.slim
h1 = t('.title')
.row
  - @posts.each do |post|
    .col-md-12
      .card.mb-3 id=dom_id(post)
        .card-body
          .card-text
            span.me-2.fw-bold = post.creator.email
            span = distance_of_time_in_words_to_now post.created_at
            hr
          h2.h5.card-title
            = post.title
          .card-text.mb-2 = post.body
          .text-right.mt-auto
            hr
            .mx-2
              span.me-2
                i.fa-regular.fa-comments
              span.me-4
                = post.count_of_comments
              span.me-2
                i.fa-regular.fa-thumbs-up
              span.me-4 = post.count_of_likes
              = link_to t('.read_more'), post, class: 'link-dark'

app/views/posts/new.html.slim
h1.h2.mb-4 = t('.title')

= simple_form_for @post do |f|
  .form_inputs
    .mb-3
      = f.input :title
    .mb-3
      = f.input :body, as: :text
    .mb-3
      = f.association :category
  .form-actions
    = f.button :submit, class: 'btn btn-primary'

app/views/posts/show.html.slim
article.col-12
  header.mb-4
    h1.fw-bolder.mb-1 = @post.title
    .d-flex.justify-content-between
      #post-section
        .text-muted.fst-italic
          = t('.posted_info', pulished_date: @post.published_date_long, author: @post.creator.email)
      #likes-section
        span.me-2 = @post.count_of_likes
        span
          - if @post.liked_by? current_user
            = link_to post_like_path(@post, @like), method: :delete, class: 'link-dark' do
              i.fa-solid.fa-thumbs-up
          - else
            = link_to post_likes_path(@post), method: :post, class: 'link-dark' do
              i.fa-regular.fa-thumbs-up

    span.badge.bg-secondary = @post.category.name

  section.mb-5
    p.fs-5.mb-2 = @post.body
= link_to posts_path(anchor: dom_id(@post)), class: 'btn btn-secondary' do
  span.me-2
    i.fa-solid.fa-backward
  = t('.to_posts_list')
hr
.lead.my-3 = t('.comments')
= render 'comment_form', comment: @new_comment, url: post_comments_path(@post) if current_user

section.mb-5
  - @comments.each do |comment, subtree|
    = render 'comment', comment: comment, subtree: subtree, new_comment: @new_comment